# Generated by Django 6.0.1 on 2026-10-02 21:05

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Excavadoras, Generadores, Andamios, Hormigoneras', max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción técnica de la categoría')),
                ('icono', models.CharField(default='fa-tools', help_text='Icono representativo UI', max_length=50)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoría de Equipo',
                'verbose_name_plural': 'Categorías de Equipos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CarroArriendo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(help_text='Usuario propietario del carro activo', on_delete=django.db.models.deletion.CASCADE, related_name='carro_activo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carro de Arriendo',
                'verbose_name_plural': 'Carros de Arriendo',
            },
        ),
        migrations.CreateModel(
            name='ContratoArriendo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_contrato', models.CharField(editable=False, max_length=30, unique=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Pago'), ('PAGADO', 'Pagado / Contrato Generado (Stock Descontado)'), ('ENTREGADO', 'Entregado en Faena / Retirado por Cliente'), ('COMPLETADO', 'Completado / Devuelto a Bodega (Stock Repuesto)'), ('CANCELADO', 'Cancelado (Stock Reincorporado)')], default='PAGADO', help_text='Estado actual del contrato en el ciclo de vida', max_length=20)),
                ('total_arriendo', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_garantias', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_general', models.DecimalField(decimal_places=2, max_digits=14)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('pagado_en', models.DateTimeField(blank=True, null=True)),
                ('entregado_en', models.DateTimeField(blank=True, null=True)),
                ('completado_en', models.DateTimeField(blank=True, null=True)),
                ('cancelado_en', models.DateTimeField(blank=True, null=True)),
                ('direccion_faena', models.CharField(blank=True, help_text='Lugar de operación de la maquinaria', max_length=255)),
                ('observaciones', models.TextField(blank=True, help_text='Anotaciones técnicas o logísticas')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_arriendo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contrato de Arriendo',
                'verbose_name_plural': 'Contratos de Arriendo',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='HistorialTransicionContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(max_length=30)),
                ('estado_nuevo', models.CharField(max_length=30)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('comentarios', models.TextField(blank=True)),
                ('cambiado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='renting.contratoarriendo')),
            ],
            options={
                'verbose_name': 'Auditoría de Transición',
                'verbose_name_plural': 'Auditorías de Transiciones',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Maquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre comercial del equipo o máquina', max_length=200)),
                ('codigo_sku', models.CharField(help_text='Identificador único SKU / Modelo', max_length=50, unique=True)),
                ('marca', models.CharField(default='Caterpillar', max_length=100)),
                ('modelo', models.CharField(default='Standard', max_length=100)),
                ('descripcion', models.TextField(help_text='Especificaciones técnicas, potencia y capacidad')),
                ('tarifa_diaria', models.DecimalField(decimal_places=2, help_text='Costo de arriendo diario en CLP o moneda base', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('monto_garantia', models.DecimalField(decimal_places=2, help_text='Monto de garantía fija requerida por unidad', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('flota_total', models.PositiveIntegerField(default=1, help_text='Cantidad total de unidades físicas que componen la flota', validators=[django.core.validators.MinValueValidator(1)])),
                ('flota_disponible', models.PositiveIntegerField(default=1, help_text='Cantidad de unidades físicas actualmente libres para arriendo')),
                ('estado_operativo', models.CharField(choices=[('DISPONIBLE', 'Disponible para Arriendo'), ('MANTENCION', 'En Mantenimiento Técnico'), ('DE_BAJA', 'De Baja / Fuera de Flota')], default='DISPONIBLE', help_text='Estado técnico operativo de la máquina', max_length=20)),
                ('imagen_url', models.URLField(blank=True, default='https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80', help_text='URL de imagen representativa de alta calidad', max_length=500)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(help_text='Categoría a la que pertenece el equipo', on_delete=django.db.models.deletion.PROTECT, related_name='maquinarias', to='renting.categoriaequipo')),
            ],
            options={
                'verbose_name': 'Maquinaria / Equipo',
                'verbose_name_plural': 'Maquinarias y Equipos',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='DetalleContratoArriendo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_equipo_congelado', models.CharField(max_length=200)),
                ('codigo_sku_congelado', models.CharField(max_length=50)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('dias_totales', models.PositiveIntegerField()),
                ('tarifa_diaria_congelada', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_garantia_congelado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal_arriendo', models.DecimalField(decimal_places=2, max_digits=14)),
                ('subtotal_garantia', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_linea', models.DecimalField(decimal_places=2, max_digits=14)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='renting.contratoarriendo')),
                ('maquinaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_asociados', to='renting.maquinaria')),
            ],
            options={
                'verbose_name': 'Detalle de Contrato',
                'verbose_name_plural': 'Detalles de Contrato',
            },
        ),
        migrations.CreateModel(
            name='ItemCarroArriendo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, help_text='Cantidad de unidades solicitadas', validators=[django.core.validators.MinValueValidator(1)])),
                ('fecha_inicio', models.DateField(help_text='Fecha de inicio del periodo de arriendo')),
                ('fecha_fin', models.DateField(help_text='Fecha de término del periodo de arriendo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='renting.carroarriendo')),
                ('maquinaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='en_carros', to='renting.maquinaria')),
            ],
            options={
                'verbose_name': 'Ítem de Carro',
                'verbose_name_plural': 'Ítems de Carro',
                'constraints': [models.UniqueConstraint(fields=('carro', 'maquinaria'), name='unique_maquinaria_por_carro')],
            },
        ),
    ]
